"""initial production schema

Revision ID: 20260510_0001
Revises:
Create Date: 2026-05-10
"""

from alembic import op
import sqlalchemy as sa

revision = "20260510_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("country", sa.String(length=120), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("industry", sa.String(length=160), nullable=False),
        sa.Column("target_leads", sa.Integer(), nullable=False),
        sa.Column("service_focus", sa.String(length=240), nullable=False),
        sa.Column("priority", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("currency", sa.String(length=12), nullable=False),
        sa.Column("source_config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("campaign_id", sa.String(length=36), sa.ForeignKey("campaigns.id"), nullable=False),
        sa.Column("business_name", sa.String(length=240), nullable=False),
        sa.Column("website_url", sa.String(length=500)),
        sa.Column("normalized_domain", sa.String(length=255)),
        sa.Column("phone", sa.String(length=80)),
        sa.Column("email", sa.String(length=180)),
        sa.Column("city", sa.String(length=120)),
        sa.Column("country", sa.String(length=120)),
        sa.Column("industry", sa.String(length=160)),
        sa.Column("google_rating", sa.Float()),
        sa.Column("review_count", sa.Integer()),
        sa.Column("address", sa.Text()),
        sa.Column("source_url", sa.String(length=500)),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("social_links", sa.JSON(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=320), nullable=False),
        sa.Column("notes", sa.Text()),
        sa.Column("contactability_score", sa.Integer(), nullable=False),
        sa.Column("business_value_score", sa.Integer(), nullable=False),
        sa.Column("industry_priority_score", sa.Integer(), nullable=False),
        sa.Column("location_priority_score", sa.Integer(), nullable=False),
        sa.Column("ai_closing_probability", sa.Integer()),
        sa.Column("website_score", sa.Integer()),
        sa.Column("final_lead_score", sa.Integer()),
        sa.Column("priority_category", sa.String(length=40)),
        sa.Column("crm_stage", sa.String(length=60), nullable=False),
        sa.Column("owner_id", sa.String(length=120)),
        sa.Column("owner_name", sa.String(length=180)),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("campaign_id", "dedupe_key", name="uq_lead_campaign_key"),
    )
    op.create_table(
        "crawl_jobs",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("campaign_id", sa.String(length=36), sa.ForeignKey("campaigns.id")),
        sa.Column("lead_id", sa.String(length=36), sa.ForeignKey("leads.id")),
        sa.Column("job_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("current_step", sa.String(length=180)),
        sa.Column("error", sa.Text()),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "websites",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("lead_id", sa.String(length=36), sa.ForeignKey("leads.id"), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("final_url", sa.String(length=500)),
        sa.Column("title", sa.String(length=500)),
        sa.Column("meta_description", sa.Text()),
        sa.Column("html_excerpt", sa.Text()),
        sa.Column("headings", sa.JSON(), nullable=False),
        sa.Column("links", sa.JSON(), nullable=False),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.Column("forms", sa.JSON(), nullable=False),
        sa.Column("cta_buttons", sa.JSON(), nullable=False),
        sa.Column("tech_stack", sa.JSON(), nullable=False),
        sa.Column("raw_metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "website_audits",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("lead_id", sa.String(length=36), sa.ForeignKey("leads.id"), nullable=False),
        sa.Column("website_id", sa.String(length=36), sa.ForeignKey("websites.id")),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("lead_priority", sa.String(length=40), nullable=False),
        sa.Column("problem_summary", sa.Text(), nullable=False),
        sa.Column("raw_checks", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "screenshots",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("website_id", sa.String(length=36), sa.ForeignKey("websites.id"), nullable=False),
        sa.Column("viewport", sa.String(length=40), nullable=False),
        sa.Column("storage_url", sa.String(length=800), nullable=False),
        sa.Column("width", sa.Integer()),
        sa.Column("height", sa.Integer()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "audit_scores",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("audit_id", sa.String(length=36), sa.ForeignKey("website_audits.id"), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "ai_reports",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("lead_id", sa.String(length=36), sa.ForeignKey("leads.id"), nullable=False),
        sa.Column("audit_id", sa.String(length=36), sa.ForeignKey("website_audits.id")),
        sa.Column("website_score", sa.Integer(), nullable=False),
        sa.Column("problem_summary", sa.Text(), nullable=False),
        sa.Column("business_risk", sa.Text(), nullable=False),
        sa.Column("improvement_opportunities", sa.JSON(), nullable=False),
        sa.Column("recommended_service", sa.String(length=240), nullable=False),
        sa.Column("estimated_project_value", sa.String(length=120), nullable=False),
        sa.Column("outreach_angle", sa.Text(), nullable=False),
        sa.Column("closing_probability", sa.Integer(), nullable=False),
        sa.Column("raw_response", sa.JSON(), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("model_name", sa.String(length=120)),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("output_schema_version", sa.String(length=40), nullable=False),
        sa.Column("token_usage", sa.JSON(), nullable=False),
        sa.Column("cost_metadata", sa.JSON(), nullable=False),
        sa.Column("failure_details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "outreach_messages",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("lead_id", sa.String(length=36), sa.ForeignKey("leads.id"), nullable=False),
        sa.Column("ai_report_id", sa.String(length=36), sa.ForeignKey("ai_reports.id")),
        sa.Column("channel", sa.String(length=60), nullable=False),
        sa.Column("subject", sa.String(length=240)),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_by_id", sa.String(length=120)),
        sa.Column("created_by_name", sa.String(length=180)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "crm_activities",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("lead_id", sa.String(length=36), sa.ForeignKey("leads.id"), nullable=False),
        sa.Column("activity_type", sa.String(length=80), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("from_stage", sa.String(length=60)),
        sa.Column("to_stage", sa.String(length=60)),
        sa.Column("actor_id", sa.String(length=120)),
        sa.Column("actor_name", sa.String(length=180)),
        sa.Column("actor_role", sa.String(length=120)),
        sa.Column("next_follow_up_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("lead_id", sa.String(length=36), sa.ForeignKey("leads.id"), nullable=False),
        sa.Column("ai_report_id", sa.String(length=36), sa.ForeignKey("ai_reports.id")),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("estimated_value", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=60), nullable=False),
        sa.Column("pdf_url", sa.String(length=800)),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True)),
        sa.Column("archived_at", sa.DateTime(timezone=True)),
        sa.Column("created_by_id", sa.String(length=120)),
        sa.Column("created_by_name", sa.String(length=180)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "enrichment_records",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("lead_id", sa.String(length=36), sa.ForeignKey("leads.id"), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("signals", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "embedding_records",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("source_object_type", sa.String(length=80), nullable=False),
        sa.Column("source_object_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("vector_id", sa.String(length=120)),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    for table in [
        "embedding_records",
        "enrichment_records",
        "proposals",
        "crm_activities",
        "outreach_messages",
        "ai_reports",
        "audit_scores",
        "screenshots",
        "website_audits",
        "websites",
        "crawl_jobs",
        "leads",
        "campaigns",
    ]:
        op.drop_table(table)
